<div id="swphp">
	<div id="swphp-content">
		<h1 id="logotipo">SWPHP</h1>
	</div>
	<div id="swphp-version">
		<?php echo SWPHP_VERSION; ?>
	</div>
	<a href="https://github.com/SmartWebAo/SWPHP" target="blank">
		<div id="swphp-repository">
			<i class="fa fa-github" aria-hidden="true"></i>
		</div>
	</a>

	<?php 
		/*
		$this->include('teste', 
			array(
				'nomes' => array(
					'Ageu Matheus',
					'Peter Dias',
					'Edmilson Andrade',
					'Edmilson Menezes'
				)
			)
		);
		*/
	?>
</div>